providers = ["node"]

[phases.setup]
cmds = ["npm install -g corepack", "corepack disable"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
