[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.install]
cmds = [
  "rm -rf node_modules",
  "npm install --force",
  "npm rebuild lightningcss"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
