providers = ["node"]

[phases.setup]
nixPkgs = ["python3", "gcc", "gnumake"]
cmds = [
  "node -v",
  "npm -v"
]

[phases.install]
cmds = [
  "npm install --platform=linux --arch=x64",
  "npm rebuild lightningcss --update-binary",
  "npm rebuild"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
