providers = ["node"]

[phases.setup]
cmds = [
  "apt-get update && apt-get install -y --no-install-recommends ca-certificates",
  "npm install -g corepack",
  "corepack disable"
]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
