providers = ["node"]

[phases.setup]
cmds = [
  "node -v",
  "npm -v",
  "npm install -g corepack",
  "corepack disable"
]

[phases.install]
cmds = [
  "npm ci --foreground-scripts",
  "npm rebuild lightningcss || true"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
