[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake", "libc.dev"]

[phases.install]
cmds = [
  "npm ci --platform=linux --arch=x64 --libc=glibc",
  "npm uninstall lightningcss",
  "npm install lightningcss --platform=linux --arch=x64 --libc=glibc",
  "npm rebuild"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
